created(1623881487.065409).
assert(chave(usuario,7)).
assert(chave(idClientes,2)).
assert(chave(idProdutos,2)).
assert(chave(funcionarios,4)).
assert(chave(fluxoDeCaixa,9)).
assert(chave(idTranscao,3)).
assert(chave(idVendas,4)).
assert(chave(idSangria,1)).
assert(chave(pessoa,6)).
assert(chave(idCliente,2)).
assert(chave(idItem,2)).
