created(1623968792.1732347).
assert(chave(usuario,7)).
assert(chave(idClientes,2)).
assert(chave(fluxoDeCaixa,9)).
assert(chave(idCliente,2)).
assert(chave(funcionarios,5)).
assert(chave(idTranscao,4)).
assert(chave(idVendas,5)).
assert(chave(idSangria,2)).
assert(chave(idItem,4)).
assert(chave(idProdutos,4)).
assert(chave(pessoa,14)).
